"""add razorpay connections

Revision ID: 838ac3e8616c
Revises: a28ed5a42e36
Create Date: 2026-09-03 12:05:51.650989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838ac3e8616c'
down_revision: Union[str, Sequence[str], None] = 'a28ed5a42e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_connections_id'), 'razorpay_connections', ['id'], unique=False)
    op.create_index(op.f('ix_razorpay_connections_merchant_id'), 'razorpay_connections', ['merchant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_razorpay_connections_merchant_id'), table_name='razorpay_connections')
    op.drop_index(op.f('ix_razorpay_connections_id'), table_name='razorpay_connections')
    op.drop_table('razorpay_connections')
    # ### end Alembic commands ###
