"""add risk alerts

Revision ID: a28ed5a42e36
Revises: 514ddd5d351a
Create Date: 2026-09-03 06:15:18.531882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28ed5a42e36'
down_revision: Union[str, Sequence[str], None] = '514ddd5d351a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_assessment_id'), 'risk_alerts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_id'), 'risk_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_merchant_id'), 'risk_alerts', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_payment_id'), 'risk_alerts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_severity'), 'risk_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_alerts_status'), 'risk_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_alerts_status'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_severity'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_payment_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_merchant_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_assessment_id'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    # ### end Alembic commands ###
